### ISSUE TITLE
Linker error on Windows

### ISSUE THREAD

**Issue by JerryAZR** [QuasarApp/Qt-Secret#97]
* OS: Windows 10
* Qt version: 6.3.0 with MinGW
* Build system: cmake

When building the project on Windows, I got the following errors:
```
23:59:17: Running steps for project Qt-Secret...
23:59:17: Persisting CMake state...
23:59:20: Starting: "C:\Qt\Tools\CMake_64\bin\cmake.exe" --build C:/Users/<username>/Documents/code/Qt/build-Qt-Secret-Desktop_Qt_6_3_0_MinGW_64_bit-Debug --target all
[1/31 2.7/sec] Building CXX object src/mini-gmp/src/CMakeFiles/QtBigint.dir/mini-gmp.c.obj
[2/31 4.0/sec] Building CXX object src/mini-gmp/src/CMakeFiles/QtBigint.dir/bigint.cpp.obj
[3/31 4.8/sec] Linking CXX static library src\mini-gmp\src\libQtBigint.a
[4/31 2.5/sec] Automatic MOC for target Qt-Secret
[5/31 2.1/sec] Automatic MOC for target QtBigintTest
[6/31 2.5/sec] Building CXX object src/mini-gmp/tests/CMakeFiles/QtBigintTest.dir/QtBigintTest_autogen/mocs_compilation.cpp.obj
[7/31 2.1/sec] Building CXX object src/CMakeFiles/Qt-Secret.dir/Qt-Secret_autogen/mocs_compilation.cpp.obj
[8/31 2.2/sec] Building CXX object src/CMakeFiles/Qt-Secret.dir/Qt-AES/qaesencryption.cpp.obj
[9/31 2.3/sec] Building CXX object src/CMakeFiles/Qt-Secret.dir/Qt-RSA/qrsaencryption.cpp.obj
[10/31 2.5/sec] Linking CXX static library src\libQt-Secret.a
[11/31 2.6/sec] Automatic MOC for target Qt-SecretTest_RSA
[12/31 2.8/sec] Building CXX object tests/CMakeFiles/Qt-SecretTest_RSA.dir/Qt-SecretTest_RSA_autogen/mocs_compilation.cpp.obj
[13/31 2.6/sec] Automatic MOC for target Qt-SecretTest_AES
[14/31 2.7/sec] Automatic MOC for target Qt-Secret-GUI
[15/31 2.9/sec] Automatic RCC for ../src/Qt-AES/res.qrc
[16/31 3.1/sec] Automatic RCC for qml.qrc
[17/31 3.2/sec] Building CXX object tests/CMakeFiles/Qt-SecretTest_AES.dir/Qt-SecretTest_AES_autogen/AUGGQPKL4Y/qrc_res.cpp.obj
[18/31 3.3/sec] Building CXX object Qt-Secret-GUI/CMakeFiles/Qt-Secret-GUI.dir/Qt-Secret-GUI_autogen/EWIEGA46WW/qrc_qml.cpp.obj
[19/31 2.9/sec] Building CXX object tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj
[20/31 2.8/sec] Linking CXX executable tests\Qt-SecretTest_RSA.exe
FAILED: tests/Qt-SecretTest_RSA.exe 
cmd.exe /C "cd . && C:\Qt\Tools\mingw1120_64\bin\g++.exe -g  tests/CMakeFiles/Qt-SecretTest_RSA.dir/Qt-SecretTest_RSA_autogen/mocs_compilation.cpp.obj tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj -o tests\Qt-SecretTest_RSA.exe -Wl,--out-implib,tests\libQt-SecretTest_RSA.dll.a -Wl,--major-image-version,0,--minor-image-version,0  src/libQt-Secret.a  C:/Qt/6.3.0/mingw_64/lib/libQt6Core.a  -lmpr  -luserenv  src/mini-gmp/src/libQtBigint.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj: in function `checkKeys(QByteArray const&, QByteArray const&, QRSAEncryption::Rsa)':
C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:53: undefined reference to `__imp__ZN14QRSAEncryptionC1ENS_3RsaE'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:71: undefined reference to `__imp__ZNK14QRSAEncryption6encodeERK10QByteArrayS2_NS_9BlockSizeE'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:72: undefined reference to `__imp__ZNK14QRSAEncryption6decodeERK10QByteArrayS2_NS_9BlockSizeE'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:79: undefined reference to `__imp__ZN14QRSAEncryption11signMessageE10QByteArrayRKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:81: undefined reference to `__imp__ZN14QRSAEncryption16checkSignMessageERK10QByteArrayS2_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:88: undefined reference to `__imp__ZN14QRSAEncryption16checkSignMessageERK10QByteArrayS2_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:95: undefined reference to `__imp__ZN14QRSAEncryption16checkSignMessageERK10QByteArrayS2_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj: in function `testGenesis(QRSAEncryption const&)':
C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:111: undefined reference to `__imp__ZNK14QRSAEncryption15generatePairKeyER10QByteArrayS1_RKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:112: undefined reference to `__imp__ZNK14QRSAEncryption6getRsaEv'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:116: undefined reference to `__imp__ZNK14QRSAEncryption15generatePairKeyER10QByteArrayS1_RKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:117: undefined reference to `__imp__ZNK14QRSAEncryption6getRsaEv'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj: in function `testCrypto(QRSAEncryption::Rsa)':
C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:128: undefined reference to `__imp__ZN14QRSAEncryptionC1ENS_3RsaE'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:134: undefined reference to `__imp__ZNK14QRSAEncryption15generatePairKeyER10QByteArrayS1_RKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: tests/CMakeFiles/Qt-SecretTest_RSA.dir/main.cpp.obj: in function `testExample()':
C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:154: undefined reference to `__imp__ZN14QRSAEncryptionC1ENS_3RsaE'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:155: undefined reference to `__imp__ZNK14QRSAEncryption15generatePairKeyER10QByteArrayS1_RKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:159: undefined reference to `__imp__ZN14QRSAEncryption11signMessageE10QByteArrayRKS0_'
C:/Qt/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/<username>/Documents/code/Qt/Qt-Secret/tests/main.cpp:161: undefined reference to `__imp__ZN14QRSAEncryption16checkSignMessageERK10QByteArrayS2_'

/* Many more similar errors */
```

## Steps

1. `git clone --recursive https://github.com/QuasarApp/Qt-Secret.git`
2. Start **Qt Creator 7.0.0**
3. Double click `Qt-Secret/CMakeLists.txt` to open the project in Qt Creator
4. Select **Desktop Qt 6.3.0 MinGW 64-bit** as the kit
5. Click on the **Build Project** button (🔨)

## Other observations

* The project builds and runs successfully with `set(BUILD_SHARED_LIBS ON)`, so its only the static library build that is failing.
* The same steps work perfectly on Linux (Pop OS 22.04), so only the Windows build is failing.
* I've tried with both static and dynamic versions of Qt 6.3.0, and dynamic Qt 5.15.2, but none of them works (same error).

**Comment by EndrII** [comment]
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)
